name: Waka Readme

on:
  schedule:
    - cron: "0 18 * * *"  # 每天台灣時間 02:00 更新 (UTC+8)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          UPDATED_DATE_FORMAT: "%Y-%m-%d %H:%M:%S"
          COMMIT_MESSAGE: "docs(readme): update wakatime metrics"
          SHOW_LINES_OF_CODE: true
          DEBUG_LOGGING: true
