name: Waka Readme

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 00:00 更新
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: "docs(readme): Update Dev Metrics (WakaTime)"
          UPDATED_DATE_FORMAT: "%Y-%m-%d %H:%M:%S"
