name: Waka Readme

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 00:00 更新
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "en"
          SECTION_NAME: "waka"
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "docs(readme): Update Dev Metrics (WakaTime)"
          COMMIT_USERNAME: "henry5720"
          COMMIT_EMAIL: "henry5720@gmail.com"
          SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%Y-%m-%d %H:%M:%S"
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "True"
          SHOW_SHORT_INFO: "True"
          IGNORED_REPOS: ""
          SYMBOL_VERSION: "1"
          DEBUG_LOGGING: "True"
