name: Waka Readme

on:
  schedule:
    # - cron: "0 18 * * *"  # 每天台灣時間 02:00 更新 (UTC+8)
    - cron: "0/5 * * * *" # 每 5 分鐘更新一次
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: "docs(readme): update dev metrics (wakatime)"
          UPDATED_DATE_FORMAT: "%Y-%m-%d %H:%M:%S"
